site_name: CREATOR documentation
site_description: Documentation for the CREATOR assembly simulator
site_url: https://creatorsim.github.io/creator-wiki
repo_url: https://github.com/creatorsim/creator
repo_name: creatorsim/creator
copyright: "&copy; 2019-2026 CREATOR Team"


nav:
  - Home: index.md
  - Web User Guide:
      - Overview: web/overview.md
      - User Interface: web/user-interface.md
      - Editor Features: web/editor-features.md
      - Assemblers: web/assemblers.md
      - Execution Control: web/execution.md
      - Gateway: web/gateway.md
      - Remote Laboratory: web/remote-lab.md
      - Arduino module (CREATino): web/arduino.md
  - CLI User Guide:
      - Overview: cli/overview.md
      - Installation: cli/installation.md
      - Command-Line Options: cli/command-line-options.md
      - Commands Reference: cli/commands-reference.md
      - Configuration: cli/configuration.md
  - Architecture Guides:
      - RISC-V: architecture/riscv.md
      - MIPS: architecture/mips.md
      - Z80: architecture/z80.md
  - Teaching Resources:
      - Overview: teaching-resources/overview.md
      - Validating program execution: teaching-resources/validator.md
      - Creating Custom Architectures: teaching-resources/custom-architectures.md
      - Setting up the Remote Laboratory: teaching-resources/remote-lab.md
      - CREATOR API (CAPI): teaching-resources/capi.md
  - Development Guide:
      - Project setup: development/setup.md
      - Architecture overview: development/overview.md
      - Devices: development/devices.md
      - Interrupts: development/interrupts.md
      - Privileged: development/privileged.md
      - Web Application: development/web.md
      - Vue 3 tricks: development/vue-tricks.md
      - Version Management: development/version-management.md


extra_css:
  - stylesheets/extra.css

extra:
  homepage: https://creatorsim.github.io/
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/creatorsim
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/creatorsim 
  analytics:
    provider: google
    property: G-3RRRR8G333


theme:
  name: material
  features:
    - content.code.copy
    - navigation.footer
    - navigation.top
    # - navigation.sections

  logo: assets/logo.png
  favicon: assets/logo.png

  icon:
    repo: fontawesome/brands/github

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: blue grey
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


plugins:
  - search
  - offline
  - glightbox

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.blocks.caption
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
